"""initial

Revision ID: 1b182b618430
Revises: None
Create Date: 2013-11-23 15:47:46.078801

"""

# revision identifiers, used by Alembic.
revision = '1b182b618430'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
