"""add user shell

Revision ID: 2eb7f6561840
Revises: 1b182b618430
Create Date: 2013-11-23 15:50:11.851808

"""

# revision identifiers, used by Alembic.
revision = '2eb7f6561840'
down_revision = '1b182b618430'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shell', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shell')
    ### end Alembic commands ###
